---
- name: Configure Erlang Yum repo
  yum_repository:
    name: rabbitmq-erlang
    description: Erlang
    baseurl: '{{ erlang_yum_baseurl }}'
    gpgcheck: '{{ erlang_yum_gpgcheck }}'
    repo_gpgcheck: '{{ erlang_yum_repo_gpgcheck }}'
    gpgkey: '{{ erlang_yum_repo_gpgkey | default(omit, true) }}'

- name: Configure RabbitMQ Yum repo
  yum_repository:
    name: rabbitmq
    description: RabbitMQ
    baseurl: '{{ rabbitmq_yum_baseurl }}'
    gpgcheck: '{{ rabbitmq_yum_gpgcheck }}'
    repo_gpgcheck: '{{ rabbitmq_yum_repo_gpgcheck }}'
    gpgkey: '{{ rabbitmq_yum_repo_gpgkey | default(omit, true) }}'

- name: Install RabbitMQ
  yum:
    name: rabbitmq-server-{{ rabbitmq_version }}
    state: present
    update_cache: true

- name: Start rabbitmq-server
  systemd:
    name: rabbitmq-server
    enabled: yes
    state: started
