---
- name: Install apt-transport-https package
  apt:
    name: apt-transport-https

- name: Ensure erlang is installed.
  package:
    name: erlang
    state: present
    
- name: Download RabbitMQ package.
  get_url:
    url: "{{ rabbitmq_deb_url }}"
    dest: "/tmp/{{ rabbitmq_deb }}"

- name: Ensure RabbitMQ is installed.
  apt:
    deb: "/tmp/{{ rabbitmq_deb }}"
    state: present
