---
- name: include rabbitmq installation tasks
  include: install-{{ ansible_os_family }}.yml

- include: plugins.yml

- include: configure.yml

- include: configure-cluster.yml
  when: rabbitmq_cluster|bool

- name: assure rabbitmq-server is started
  service:
    name: rabbitmq-server
    enabled: true
    state: started

- include: vhosts.yml

- include: users.yml

- include: cluster.yml
  when: rabbitmq_cluster|bool and rabbitmq_nodename != rabbitmq_cluster_master

- name: Download rabbitmqadmin
  get_url:
    url: http://127.0.0.1:15672/cli/rabbitmqadmin
    dest: /bin/rabbitmqadmin
    mode: '0755'
  when: rabbitmqadmin|bool
