---
- name: restart rabbitmq-server
  service:
    name: rabbitmq-server
    enabled: true
    state: restarted

- name: remove non-master-node on master
  command: "rabbitmqctl forget_cluster_node rabbit@{{ inventory_hostname_short }}"
  delegate_to: "{{ rabbitmq_cluster_master_node }}"
  ignore_errors: true
