---
- name: Converge
  hosts: all
  become: true

  vars:
    rabbitmqadmin: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: m1cka.ansible-role-rabbitmq

  post_tasks:
    - name: check rabbitmq version
      shell: 'rpm -qa |grep "rabbitmq-server-3.8.16-1.el7.noarch"'
      changed_when: False
